version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: 'qdrant'
    restart: always
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    ports:
      - 6333:6333
  redis:
    image: redis:7.0-alpine
    container_name: 'redis'
    command: redis-server --save 20 1
    volumes: 
      - ./data/redis_storage:/data
    restart: always
    ports:
      - 6379:6379

